############# English navigation ##############

# main menu
[[main]]
weight = 1
url = ""
name = "Home"
hasChildren = true

  [[main]]
  parent = "Home"
  weight = 1
  url = "homepage/list/"
  name = "List layout"

  [[main]]
  parent = "Home"
  weight = 2
  url = "homepage/grid/"
  name = "Grid layout"

[[main]]
weight = 2
url = "#"
name = "Browse"
hasChildren = true

  [[main]]
  parent = "Browse"
  weight = 1
  url = "speaker/"
  name = "Speakers"
  
  [[main]]
  parent = "Browse"
  weight = 2
  url = "tags/"
  name = "Tags"
  
  #[[main]]
  # parent = "Pages"
  # weight = 3
  # url = "tags/photography/"
  # name = "Tag Single"
  
  [[main]]
  parent = "Browse"
  weight = 4
  url = "categories/"
  name = "Categories"
  
  #[[main]]
  # parent = "Pages"
  # weight = 5
  # url = "categories/lifestyle/"
  # name = "Category Single"
  
  #[[main]]
  # parent = "Pages"
  # weight = 6
  # url = "elements/"
  # name = "Elements"

[[main]]
weight = 3
url = "about/"
name = "About"
  
[[main]]
weight = 4
url = "contact/"
name = "Contact"

[[main]]
weight = 5
url = "#"
name = "Participate"
hasChildren = true

  [[main]]
  parent = "Participate"
  weight = 1
  url = "pitch-talk/"
  name = "Pitch a Talk"
  
  [[main]]
  parent = "Participate"
  weight = 2
  url = "sponsor/"
  name = "Sponsor"

############################# Footer Menu ########################
[[footer]]
weight = 1
url = "about/"
name = "About"

[[footer]]
weight = 2
url = "speaker/"
name = "Speakers"

[[footer]]
weight = 3
url = "privacy/"
name = "Privacy"

[[footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"